version: "3"
services:
  postgres:
    image: postgres:9.6.6-alpine
    ports:
      - 5432:5432
    env_file: .env
    environment:
      - POSTGRES_DB=kashikari_development

  redis:
    image: redis:3.2.11-alpine
    ports:
      - 6379:6379
