default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV["POSTGRES_HOST"].presence || "localhost" %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>

development:
  <<: *default
  database: kashikari_development

test:
  <<: *default
  database: kashikari_test

heroku:
  <<: *default
  database: kashikari_heroku

production:
  <<: *default
  database: kashikari_production
